"""empty message

Revision ID: 1a052f3562bf
Revises: c4ef59335846
Create Date: 2022-03-30 02:31:02.625067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a052f3562bf'
down_revision = 'c4ef59335846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planet_name', sa.String(length=150), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('density', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planet')
    # ### end Alembic commands ###
