"""empty message

Revision ID: 985fed8b6bdb
Revises: aca46be025c1
Create Date: 2022-03-30 02:54:00.303446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '985fed8b6bdb'
down_revision = 'aca46be025c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoritescharacter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favoritescharacter')
    # ### end Alembic commands ###
