"""empty message

Revision ID: aca46be025c1
Revises: 1a052f3562bf
Create Date: 2022-03-30 02:47:31.059948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aca46be025c1'
down_revision = '1a052f3562bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_name', sa.String(length=150), nullable=False),
    sa.Column('vehicle_model', sa.String(length=150), nullable=False),
    sa.Column('vehicle_manufacturer', sa.String(length=150), nullable=False),
    sa.Column('vehicle_pilot', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle')
    # ### end Alembic commands ###
